name: managehostel
description: A hostel management Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  pdf: ^3.10.7
  path_provider: ^2.1.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  permission_handler: ^11.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
